davidahouse/stampede-worker

lib/workingDirectory.js

This PR modifies the `git checkout` logic and allows the worker to receive `latest` as a SHA and when received will perform a simple `git checkout branch` instead of checking out the specific SHA commit. Now jobs can be configured to pull the latest commit and not have to generate SHAs dynamically.
closes #115

✨ Support checking out to latest in a branch

---

bin/stampede-worker.js

This PR adds new environment variables for pull requests so that tasks can use them. Title, body length, milestone and labels are now available as environment variables to tasks when the task was triggered from a pull request.
closes #117

✨ New environment variables for PR details

---

lib/workingDirectory.js

This PR updates the worker to use the access token sent from the server when performing a https clone. This allows the system to clone a repo where the GitHub app has been granted permission without having to grant a specific user access and cloning via ssh. Now both are possible depending on the repo and setup desired.
closes #122

✨ now using access token for https clones

---

lib/workingDirectory.js

This PR now returns a task failure if we get a clone error. Before it would continue with the task and possibly not fail in a clear way.
closes #125

✨ Now returning clone errors as a failed task

---

lib/workingDirectory.js

This PR fixes a bug found in the gitMerge method that causes the task to fail silently.

🐛 fixed bug in gitmerge method

---

bin/stampede-worker.js

This PR looks for a release body in the task details and will write it out to a file for shell based tasks. The default filename is `releasebody.txt`. Given that release notes can be quite extensive, it is best not written to an environment variable, but directly to a file. Also many tools where release notes are used can read directly from files anyway.
closes #133

✨ Now writing out the release body to a file if received

---

bin/stampede-worker.js
lib/executionConfig.js
package-lock.json
package.json

This PR adds support for artifacts in the worker for shell script tasks. The task must create a csv file that contains a title, url and type for each artifact the task has created. Note that url should be something accessible by users via portal or GitHub check. The default file name is `artifacts.csv`, but this can be configured at the worker or task level via the `artifactListFile` property.
closes #137

✨Support for artifacts via csv file list

---

bin/stampede-worker.js
lib/workingDirectory.js

This PR fixes a bug when trying to clone using the access token. Also makes https cloning the default.
closes #141

🐛 Fixed issue when cloning using https

---

lib/workingDirectory.js

This PR changes the merge behavior when cloning PRs. Now the system will use the base branch name and not the sha. Unfortunately we can't trust the sha to always be the latest for the base. This might get locked to a single sha when the PR is created, not sure.
closes #143

♻️ Use name not sha for merging from base

---

bin/stampede-worker.js

This PR fixes an issue where the task wouldn't get a finished_at date when there was an issue cloning into the working folder. This cases the tasks not to show up in certain places in the UI since it filters by finished at dates.

🐛Fixed missing finished at date for working folder failures

---

lib/workingDirectory.js

This PR adds an error log written to the workspace when the clone fails for some reason. This allows for easier debugging instead of trying to find it in the worker logs.
closes #147

👷‍♂️ Write out a clone error log

---

bin/stampede-worker.js
lib/workingDirectory.js

This PR changes the behavior when performing the git clone, checkout and merge commands. Now they are all checked for failure and will fail the task with a more descriptive error instead of letting the command attempt to execute and produce confusing or possibly invalid results.
closes #144

👷‍♂️ Fail more clearly for git clone and merge errors

---

lib/workingDirectory.js

This PR adds verbose logging for the commit details for a branch checkout. These details are used to fill in the gaps if the task was started based on the latest commit of a branch.

🔊Added commit details logging

---

lib/workingDirectory.js

This PR changes the commit message to use subject instead of body when capturing the commit details from a branch task and latest commit.
closes #163

♻️ Use subject instead of body for commit message

---

.gitignore
.ubolt.yaml
bin/stampede-worker.js

This PR adds more logic to the graceful shutdown to handle when a task is currently running. Now the worker will stop the task, update it back to `queued` and then stop the worker. This allows the task to be processed by a separate worker. To gracefully shutdown and re-queue the task, a SIGHUP signal must be sent to the worker, not SIGKILL or SIGINT. You can still send the latter 2 if you don't care about the currently running task.
closes #176

✨ Improved graceful shutdown

---

bin/stampede-worker.js

This PR Updates the worker to allow for loading contents & metadata for artifacts that specify json files for these. This allows Stampede to store certain contents in its database directly instead of relying solely on external file hosting. Storing contents is limited to JSON documents and care should be taken to not store huge amounts of data. But for most use-cases this shouldn't be a problem.
closes #180

✨ Worker now returns metadata & artifact contents if specified

---

lib/workingDirectory.js

This PR updates the operations for making the working folder and cloning the repo so they have their working directory set to the workspace root. If the process somehow gets its working directory changed, these operations can fail with an error: shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory. This should no longer happen since the workspace root should always be there.
Closes #175 but not really a timing error.

🐛 Set working directory to known good directory before exec operations

---

bin/stampede-worker.js
lib/workingDirectory.js

This PR changes how the working directory is prepared when cloning repositories. Instead of doing a full clone and then checking out the correct commit, this change will clone to a specific branch or tag and then checkout to the commit. This change also adds depth and single branch operations to the clone to improve performance and limit the amount of data pulled from the git repository.
closes #168

♻️Refactor working directory preparation

---

lib/workingDirectory.js

This PR fixes a bug that was causing an error after getting the last commit details for a release task: 
```
Error in handle task TypeError: Cannot set property 'sha' of undefined
```
closes #189

🐛 Fixed bug trying to get last commit for release clones

---

bin/stampede-worker.js
lib/executionConfig.js

This PR adds support for returning the summaryTable json file if found in the working directory. You can configure the filename in the worker config with the `summaryTableFile` property. The default is `summarytable.json`. The format of the json file is detailed in #197. If this file is found in the working directory, the contents are added to the key `summaryTable` in the task details. This is then rendered by the server in the UI or used in notification channels and GitHub check updates.
closes #197

✨ Added support for summaryTable
